// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NormfallstudieDatenservice.Models;

namespace NormfallstudieDatenservice.Migrations
{
    [DbContext(typeof(EasyjetContext))]
    [Migration("20190703084318_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("NormfallstudieDatenservice.Models.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("DestinationId");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("NormfallstudieDatenservice.Models.EasyjetFlight", b =>
                {
                    b.Property<int>("EasyjetFlightId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Date");

                    b.Property<int>("EmptyPlaces");

                    b.Property<int?>("EndDestinationDestinationId");

                    b.Property<int?>("StartDestinationDestinationId");

                    b.HasKey("EasyjetFlightId");

                    b.HasIndex("EndDestinationDestinationId");

                    b.HasIndex("StartDestinationDestinationId");

                    b.ToTable("EasyjetFlights");
                });

            modelBuilder.Entity("NormfallstudieDatenservice.Models.EasyjetFlight", b =>
                {
                    b.HasOne("NormfallstudieDatenservice.Models.Destination", "EndDestination")
                        .WithMany()
                        .HasForeignKey("EndDestinationDestinationId");

                    b.HasOne("NormfallstudieDatenservice.Models.Destination", "StartDestination")
                        .WithMany()
                        .HasForeignKey("StartDestinationDestinationId");
                });
#pragma warning restore 612, 618
        }
    }
}
