// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NormfallstudieDatenservice.Models;

namespace NormfallstudieDatenservice.Migrations.Swiss
{
    [DbContext(typeof(SwissContext))]
    partial class SwissContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("NormfallstudieDatenservice.Models.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("DestinationId");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("NormfallstudieDatenservice.Models.SwissFlight", b =>
                {
                    b.Property<int>("SwissFlightId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Date");

                    b.Property<int>("EmptyPlaces");

                    b.Property<int?>("EndDestinationDestinationId");

                    b.Property<int?>("StartDestinationDestinationId");

                    b.HasKey("SwissFlightId");

                    b.HasIndex("EndDestinationDestinationId");

                    b.HasIndex("StartDestinationDestinationId");

                    b.ToTable("SwissFlights");
                });

            modelBuilder.Entity("NormfallstudieDatenservice.Models.SwissFlight", b =>
                {
                    b.HasOne("NormfallstudieDatenservice.Models.Destination", "EndDestination")
                        .WithMany()
                        .HasForeignKey("EndDestinationDestinationId");

                    b.HasOne("NormfallstudieDatenservice.Models.Destination", "StartDestination")
                        .WithMany()
                        .HasForeignKey("StartDestinationDestinationId");
                });
#pragma warning restore 612, 618
        }
    }
}
