// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NormfallstudieDatenservice.Models;

namespace NormfallstudieDatenservice.Migrations.Ibis
{
    [DbContext(typeof(IbisContext))]
    partial class IbisContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("NormfallstudieDatenservice.Models.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("DestinationId");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("NormfallstudieDatenservice.Models.IbisNight", b =>
                {
                    b.Property<int>("IbisNightId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Date");

                    b.Property<int?>("DestinationId");

                    b.Property<int>("EmptyPlaces");

                    b.HasKey("IbisNightId");

                    b.HasIndex("DestinationId");

                    b.ToTable("IbisNights");
                });

            modelBuilder.Entity("NormfallstudieDatenservice.Models.IbisNight", b =>
                {
                    b.HasOne("NormfallstudieDatenservice.Models.Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId");
                });
#pragma warning restore 612, 618
        }
    }
}
